### ISSUE TITLE
Handsontable.eventManager is undefined

### ISSUE THREAD

**Issue by VioLoustic** [handsontable/hot-table#48] opened 2017-10-12 10:34 UTC
I'm using the latest master version of `<hot-table>`
When I implemented `<hot-table>` as a web component in my sample project, the handsontable was not displayed because the console throw error as below:
> hot-table.js:54 Uncaught TypeError: Cannot set property 'isHotTableEnv' of undefined
>     at HTMLElement.<anonymous> (hot-table.js:54)

I tried to comment out the below source code (hot-table.js)
```
        this.hot.isHotTableEnv = true;
        Handsontable.eventManager.isHotTableEnv = this.hot.isHotTableEnv;
```
Then the table was shown properly.
Could you please provide me a sample source code without modifying hot-table.js?
I need to run hot-table in JavaScript (not AngularJS)

Thank you very much!

**Comment by AMBudnik** [comment] 2017-10-16 09:05
Hi @VioLoustic 

the `eventManager` has been renamed to `EventManager` in version [1.11.0](https://docs.handsontable.com/pro/1.11.0/tutorial-release-notes.html)

**Comment by VioLoustic** [comment] 2017-10-16 09:44
Hi @AMBudnik 
Please refer to: https://github.com/handsontable/hot-table/blob/a0e61363d63b1394a84457d0159f020d949974f3/src/hot-table.js#L54
I'm using master version of hot-table, not pro version.
Could you check it again?
Thank you!

**Comment by AMBudnik** [comment] 2017-11-06 09:19
I am sorry. I did not get a notification about the comment.

Have you already managed to fix the issue?

**Comment by mohsini172** [comment] 2017-12-23 19:46
I'm having same problem right click is not working for me. Anyone find solution?

**Comment by warpech** [comment] 2017-12-29 21:18
@AMBudnik `<hot-table>` wraps Handsontable CE 0.24.3, which still uses `Handsontable.eventManager`.

The problem reported by @mohsini172 seems to be unrelated. I have created a separate issue for it: https://github.com/handsontable/hot-table/issues/51. Please follow that one for the context menu problem.

I would like to help but I cannot reproduce the problem explained by @VioLoustic. Closing this issue as not reproducible. If the issue prevails, please provide accurate steps to reproduce or more information that helps to find the reason.

**Closed by warpech** 2017-12-29 21:18 UTC

**Comment by mringler** [comment] 2018-04-28 21:53
This happened to me when using ngHandsontable with a new handsontable version.

Note that once loaded, ngHandsontable will cause this issue even on regular HOT-tables, since it adds a non-compatible hook to the global Handsontable object.
